// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfLotto.Data;

#nullable disable

namespace WpfLotto.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240603094836_Lotto")]
    partial class Lotto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WpfLotto.Models.Sorsolas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("szam1")
                        .HasColumnType("int");

                    b.Property<int>("szam2")
                        .HasColumnType("int");

                    b.Property<int>("szam3")
                        .HasColumnType("int");

                    b.Property<int>("szam4")
                        .HasColumnType("int");

                    b.Property<int>("szam5")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sorsolasok");
                });
#pragma warning restore 612, 618
        }
    }
}
